
# MAIN
IP_ADDRESS = '192.168.12.1'

# ANDROID
ANDROID_BLUETOOTH_PORT = 1
ANDROID_BLUETOOTH_BACKLOG = 1
ANDROID_BUFFER_SIZE = 1024
ANDROID_HOST_MAC = 'B8:27:EB:2E:B7:20'

# CAR
CAR_PORT = '/dev/ttyUSB0'
CAR_BAUD_RATE = 115200
CAR_TIMEOUT = 0
CAR_RECIVER_ID = ['AND', 'ALG']

# PI CAMERA
CAMERA_PROCESSING_ADDRESS = 'tcp://192.168.12.13:5555'
CAMERA_RESOLUTION_X = 640
CAMERA_RESOLUTION_Y = 480
CAMERA_RECEIVER = ['AND', 'ALG']

# ALGO SERVER
SERVER_IP_ADDRESS = IP_ADDRESS
SERVER_PORT = 10003
SERVER_BUFFER_SIZE = 1024

# IMAGE PROCESSING SERVER
# IMGPROC_IP_ADDRESS = IP_ADDRESS
# IMGPROC_PORT = 10005
# IMGPROC_BUFFER_SIZE = 1024

# NETWORKING
# NETWORKING_PACKAGE_NAMING = {
#     'STM': "RC-Car",
#     'AND': "ANDROID",
#     'ALG': "ALGORITHM PC",
#     'IMG': "PI-CAMERA",
#     'CPC': "CAMERA-PC",
#     'OTH': "OTHER"
# }
